services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: rails_app
    restart: always
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/mydatabase"
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY} # Load from environment variable
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    command: ["./api/bin/rails", "server"]

volumes:
  postgres_data:
    driver: local
