version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: photo_app
      POSTGRES_PASSWORD: secret

  redis:
    image: redis:alpine

  api:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://photo_app:secret@db:5432/photo_app_development
      REDIS_URL: redis://redis:6379

  client-react:
    build: ./client-react
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://api:3000
    depends_on:
      - api

  client-vue:
    build: ./client-vue
    ports:
      - "3002:8080"
    environment:
      - VUE_APP_API_URL=http://api:3000
    depends_on:
      - api

volumes:
  postgres_data: